import 'bloc/success_bloc.dart';import 'models/success_model.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_elevated_button.dart';class SuccessScreen extends StatelessWidget {const SuccessScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SuccessBloc>(create: (context) => SuccessBloc(SuccessState(successModelObj: SuccessModel()))..add(SuccessInitialEvent()), child: SuccessScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<SuccessBloc, SuccessState>(builder: (context, state) {return SafeArea(child: Scaffold(backgroundColor: appTheme.gray10001, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 35.v), child: Column(children: [CustomImageView(imagePath: ImageConstant.imgGroupIndigoA10001277x300, height: 277.v, width: 300.h), SizedBox(height: 48.v), Text("msg_transaction_complete".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 18.v), Container(width: 253.h, margin: EdgeInsets.only(left: 36.h, right: 37.h), child: Text("msg_your_transaction".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumOnPrimaryContainer_1.copyWith(height: 1.71))), SizedBox(height: 76.v), CustomElevatedButton(text: "lbl_continue".tr), SizedBox(height: 27.v), Text("lbl_go_to_home".tr, style: CustomTextStyles.titleMedium16_1), SizedBox(height: 5.v)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.fromLTRB(24.h, 8.v, 311.h, 8.v), onTap: () {onTapClose(context);})); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
