import 'bloc/settings_bloc.dart';import 'models/settings_model.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_subtitle.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_elevated_button.dart';import 'package:hari_s_application3/widgets/custom_switch.dart';class SettingsScreen extends StatelessWidget {const SettingsScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SettingsBloc>(create: (context) => SettingsBloc(SettingsState(settingsModelObj: SettingsModel()))..add(SettingsInitialEvent()), child: SettingsScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 32.v), child: Column(children: [_buildGeneral(context), SizedBox(height: 57.v), _buildSecurity(context), Spacer(), CustomElevatedButton(text: "lbl_save".tr, buttonStyle: CustomButtonStyles.fillIndigoA), SizedBox(height: 16.v), Text("msg_2021_stockit".tr, style: theme.textTheme.bodySmall), SizedBox(height: 26.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapClose(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_settings".tr)); } 
/// Section Widget
Widget _buildGeneral(BuildContext context) { return Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_general".tr, style: CustomTextStyles.labelLargeGray600)), SizedBox(height: 31.v), _buildContactUs(context, text: "lbl_notifications".tr), SizedBox(height: 24.v), _buildContactUs(context, text: "lbl_contact_us".tr)]); } 
/// Section Widget
Widget _buildSecurity(BuildContext context) { return Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_security".tr, style: CustomTextStyles.labelLargeGray600)), SizedBox(height: 30.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 5.v), child: Text("msg_fingerprint_and".tr, style: theme.textTheme.titleSmall)), BlocSelector<SettingsBloc, SettingsState, bool?>(selector: (state) => state.isSelectedSwitch, builder: (context, isSelectedSwitch) {return CustomSwitch(value: isSelectedSwitch, onChange: (value) {context.read<SettingsBloc>().add(ChangeSwitchEvent(value: value));});})]), SizedBox(height: 29.v), Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_privacy_policy".tr, style: theme.textTheme.titleSmall), SizedBox(height: 10.v), Text("msg_choose_what_data".tr, style: theme.textTheme.bodySmall)]), CustomImageView(imagePath: ImageConstant.imgArrowRightBlueGray100, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(top: 6.v, bottom: 13.v))]), SizedBox(height: 22.v), _buildContactUs(context, text: "lbl_legal".tr)]); } 
/// Common widget
Widget _buildContactUs(BuildContext context, {required String text, }) { return Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Padding(padding: EdgeInsets.only(top: 3.v, bottom: 2.v), child: Text(text, style: theme.textTheme.titleSmall!.copyWith(color: theme.colorScheme.onPrimaryContainer))), CustomImageView(imagePath: ImageConstant.imgArrowRightBlueGray100, height: 24.adaptSize, width: 24.adaptSize)]); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
