import 'bloc/language_bloc.dart';import 'models/language_model.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_subtitle.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_text_form_field.dart';class LanguageScreen extends StatelessWidget {const LanguageScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<LanguageBloc>(create: (context) => LanguageBloc(LanguageState(languageModelObj: LanguageModel()))..add(LanguageInitialEvent()), child: LanguageScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.all(24.h), child: Column(children: [BlocSelector<LanguageBloc, LanguageState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomTextFormField(controller: searchController, hintText: "lbl_search".tr, hintStyle: CustomTextStyles.bodyMediumPink500_1, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(24.h, 20.v, 16.h, 20.v), child: CustomImageView(imagePath: ImageConstant.imgUserPink500, height: 24.adaptSize, width: 24.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 64.v), contentPadding: EdgeInsets.only(top: 23.v, right: 30.h, bottom: 23.v));}), SizedBox(height: 32.v), _buildItemRow1(context), SizedBox(height: 15.v), _buildItemRow(context, userImage: ImageConstant.imgChina, spanishText: "lbl_chinese".tr), SizedBox(height: 15.v), _buildItemRow(context, userImage: ImageConstant.imgSpain, spanishText: "lbl_spanish".tr), SizedBox(height: 15.v), _buildItemRow(context, userImage: ImageConstant.imgFrance, spanishText: "lbl_french".tr), SizedBox(height: 15.v), _buildItemRow(context, userImage: ImageConstant.imgJapan, spanishText: "lbl_japanese".tr), SizedBox(height: 4.v)])), bottomNavigationBar: _buildItemRow3(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapClose(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_language".tr)); } 
/// Section Widget
Widget _buildItemRow1(BuildContext context) { return Container(padding: EdgeInsets.all(24.h), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgUnitedStates, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h, top: 5.v), child: Text("lbl_english".tr, style: CustomTextStyles.titleSmallOnErrorContainer_1)), Spacer(), CustomImageView(imagePath: ImageConstant.imgCheckmarkGreen50, height: 18.adaptSize, width: 18.adaptSize, margin: EdgeInsets.only(right: 6.h, bottom: 6.v))])); } 
/// Section Widget
Widget _buildItemRow3(BuildContext context) { return Container(margin: EdgeInsets.only(left: 48.h, right: 48.h, bottom: 96.v), decoration: AppDecoration.outlineGray100.copyWith(borderRadius: BorderRadiusStyle.circleBorder24), child: Row(mainAxisAlignment: MainAxisAlignment.center, mainAxisSize: MainAxisSize.min, children: [CustomImageView(imagePath: ImageConstant.imgVietnam, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h, top: 3.v, bottom: 2.v), child: Text("lbl_vietnamese".tr, style: CustomTextStyles.titleSmallGray900_1)), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightBlueGray100, height: 24.adaptSize, width: 24.adaptSize)])); } 
/// Common widget
Widget _buildItemRow(BuildContext context, {required String userImage, required String spanishText, }) { return Container(padding: EdgeInsets.all(23.h), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder24), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: userImage, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h, top: 5.v), child: Text(spanishText, style: CustomTextStyles.titleSmallGray900_1.copyWith(color: appTheme.gray900))), Spacer(), CustomImageView(imagePath: ImageConstant.imgArrowRightBlueGray100, height: 24.adaptSize, width: 24.adaptSize)])); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
