import 'bloc/referral_code_bloc.dart';import 'models/referral_code_model.dart';import 'package:dotted_border/dotted_border.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_subtitle.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_elevated_button.dart';class ReferralCodeScreen extends StatelessWidget {const ReferralCodeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<ReferralCodeBloc>(create: (context) => ReferralCodeBloc(ReferralCodeState(referralCodeModelObj: ReferralCodeModel()))..add(ReferralCodeInitialEvent()), child: ReferralCodeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<ReferralCodeBloc, ReferralCodeState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 28.v), child: Column(children: [SizedBox(height: 14.v), _buildVector(context), SizedBox(height: 52.v), Text("lbl_refer_earn".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 20.v), Container(width: 233.h, margin: EdgeInsets.symmetric(horizontal: 46.h), child: Text("msg_share_this_code".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.bodyMediumGray600.copyWith(height: 1.71))), SizedBox(height: 55.v), _buildCode(context)])), bottomNavigationBar: _buildReferFriend(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapClose(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_referral_code".tr)); } 
/// Section Widget
Widget _buildVector(BuildContext context) { return SizedBox(height: 238.v, width: 300.h, child: Stack(alignment: Alignment.topCenter, children: [CustomImageView(imagePath: ImageConstant.imgVector, height: 173.v, width: 300.h, alignment: Alignment.bottomCenter), CustomImageView(imagePath: ImageConstant.imgFramePrimarycontainer, height: 215.v, width: 229.h, alignment: Alignment.topCenter)])); } 
/// Section Widget
Widget _buildCode(BuildContext context) { return Container(decoration: AppDecoration.outlinePinkA.copyWith(borderRadius: BorderRadiusStyle.roundedBorder16), child: DottedBorder(color: appTheme.pinkA100, padding: EdgeInsets.only(left: 1.h, top: 1.v, right: 1.h, bottom: 1.v), strokeWidth: 1.h, radius: Radius.circular(16), borderType: BorderType.RRect, dashPattern: [8], child: Padding(padding: EdgeInsets.symmetric(horizontal: 23.h, vertical: 19.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.end, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text("lbl_tradebase2".tr, style: CustomTextStyles.titleMedium16_1)), Spacer(), CustomImageView(imagePath: ImageConstant.imgUser1, height: 24.adaptSize, width: 24.adaptSize), Padding(padding: EdgeInsets.only(left: 8.h, top: 5.v), child: Text("lbl_copy_code".tr, style: CustomTextStyles.titleSmallPink500))])))); } 
/// Section Widget
Widget _buildReferFriend(BuildContext context) { return CustomElevatedButton(text: "lbl_refer_friend".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 60.v)); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
