import 'bloc/login_active_state_bloc.dart';import 'models/login_active_state_model.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/core/utils/validation_functions.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_elevated_button.dart';import 'package:hari_s_application3/widgets/custom_floating_text_field.dart';import 'package:hari_s_application3/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class LoginActiveStateScreen extends StatelessWidget {LoginActiveStateScreen({Key? key}) : super(key: key);

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

static Widget builder(BuildContext context) { return BlocProvider<LoginActiveStateBloc>(create: (context) => LoginActiveStateBloc(LoginActiveStateState(loginActiveStateModelObj: LoginActiveStateModel()))..add(LoginActiveStateInitialEvent()), child: LoginActiveStateScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 27.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(left: 4.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgGroup10, height: 27.v, width: 31.h, margin: EdgeInsets.only(bottom: 3.v)), Padding(padding: EdgeInsets.only(left: 2.h, top: 7.v), child: Text("lbl_arrow_trade".tr, style: CustomTextStyles.titleMediumKodchasanPrimary))])), SizedBox(height: 42.v), Text("msg_let_s_sign_you_in".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 19.v), Text("msg_welcome_back_you_ve".tr, style: CustomTextStyles.bodyMediumGray600), SizedBox(height: 32.v), _buildInputs(context), Spacer(), CustomElevatedButton(text: "lbl_login".tr), SizedBox(height: 29.v), Align(alignment: Alignment.center, child: RichText(text: TextSpan(children: [TextSpan(text: "msg_dont_s_have_an_account2".tr, style: CustomTextStyles.bodyMediumOnPrimaryContainer), TextSpan(text: "lbl_sign_up".tr, style: CustomTextStyles.titleSmallOnPrimary)]), textAlign: TextAlign.left)), SizedBox(height: 13.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.fromLTRB(24.h, 8.v, 311.h, 8.v), onTap: () {onTapClose(context);})); } 
/// Section Widget
Widget _buildInputs(BuildContext context) { return Column(children: [BlocSelector<LoginActiveStateBloc, LoginActiveStateState, TextEditingController?>(selector: (state) => state.emailController, builder: (context, emailController) {return CustomFloatingTextField(controller: emailController, labelText: "lbl_email_address".tr, labelStyle: theme.textTheme.bodyLarge!, hintText: "lbl_email_address".tr, textInputType: TextInputType.emailAddress, validator: (value) {if (value == null || (!isValidEmail(value, isRequired: true))) {return "err_msg_please_enter_valid_email".tr;} return null;});}), SizedBox(height: 8.v), BlocBuilder<LoginActiveStateBloc, LoginActiveStateState>(builder: (context, state) {return CustomTextFormField(controller: state.languageController, hintText: "lbl".tr, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, suffix: InkWell(onTap: () {context.read<LoginActiveStateBloc>().add(ChangePasswordVisibilityEvent(value: !state.isShowPassword));}, child: Container(margin: EdgeInsets.fromLTRB(30.h, 30.v, 24.h, 20.v), child: CustomImageView(imagePath: ImageConstant.imgEye, height: 24.adaptSize, width: 24.adaptSize))), suffixConstraints: BoxConstraints(maxHeight: 76.v), validator: (value) {if (value == null || (!isValidPassword(value, isRequired: true))) {return "err_msg_please_enter_valid_password".tr;} return null;}, obscureText: state.isShowPassword, contentPadding: EdgeInsets.only(left: 24.h, top: 18.v, bottom: 18.v));})]); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
