import '../select_payment_method_screen/widgets/debitcardlist_item_widget.dart';import '../select_payment_method_screen/widgets/paymentmethod_item_widget.dart';import 'bloc/select_payment_method_bloc.dart';import 'models/debitcardlist_item_model.dart';import 'models/paymentmethod_item_model.dart';import 'models/select_payment_method_model.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_title.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_elevated_button.dart';class SelectPaymentMethodScreen extends StatelessWidget {const SelectPaymentMethodScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SelectPaymentMethodBloc>(create: (context) => SelectPaymentMethodBloc(SelectPaymentMethodState(selectPaymentMethodModelObj: SelectPaymentMethodModel()))..add(SelectPaymentMethodInitialEvent()), child: SelectPaymentMethodScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray50, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 32.v), child: Column(children: [_buildDebitCardList(context), SizedBox(height: 41.v), _buildPaymentMethodColumn(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildContinueButton(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapClose(context);}), centerTitle: true, title: AppbarTitle(text: "lbl_payment_method".tr)); } 
/// Section Widget
Widget _buildDebitCardList(BuildContext context) { return BlocSelector<SelectPaymentMethodBloc, SelectPaymentMethodState, SelectPaymentMethodModel?>(selector: (state) => state.selectPaymentMethodModelObj, builder: (context, selectPaymentMethodModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: selectPaymentMethodModelObj?.debitcardlistItemList.length ?? 0, itemBuilder: (context, index) {DebitcardlistItemModel model = selectPaymentMethodModelObj?.debitcardlistItemList[index] ?? DebitcardlistItemModel(); return DebitcardlistItemWidget(model);});}); } 
/// Section Widget
Widget _buildPaymentMethodColumn(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("lbl_another_payment".tr, style: CustomTextStyles.labelLargeGray600), SizedBox(height: 22.v), BlocSelector<SelectPaymentMethodBloc, SelectPaymentMethodState, SelectPaymentMethodModel?>(selector: (state) => state.selectPaymentMethodModelObj, builder: (context, selectPaymentMethodModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 24.v);}, itemCount: selectPaymentMethodModelObj?.paymentmethodItemList.length ?? 0, itemBuilder: (context, index) {PaymentmethodItemModel model = selectPaymentMethodModelObj?.paymentmethodItemList[index] ?? PaymentmethodItemModel(); return PaymentmethodItemWidget(model);});})]); } 
/// Section Widget
Widget _buildContinueButton(BuildContext context) { return CustomElevatedButton(text: "lbl_continue".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 60.v)); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
