import 'bloc/create_authentication_face_id_bloc.dart';import 'models/create_authentication_face_id_model.dart';import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_elevated_button.dart';class CreateAuthenticationFaceIdScreen extends StatelessWidget {const CreateAuthenticationFaceIdScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<CreateAuthenticationFaceIdBloc>(create: (context) => CreateAuthenticationFaceIdBloc(CreateAuthenticationFaceIdState(createAuthenticationFaceIdModelObj: CreateAuthenticationFaceIdModel()))..add(CreateAuthenticationFaceIdInitialEvent()), child: CreateAuthenticationFaceIdScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<CreateAuthenticationFaceIdBloc, CreateAuthenticationFaceIdState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 44.h, vertical: 36.v), child: Column(children: [Text("lbl_setup_face_id".tr, style: CustomTextStyles.headlineSmallIndigo900), SizedBox(height: 17.v), Container(width: 209.h, margin: EdgeInsets.only(left: 38.h, right: 39.h), child: Text("msg_you_can_use_face".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyMedium!.copyWith(height: 1.71))), SizedBox(height: 70.v), _buildFrame(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildScanMyFace(context)));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.fromLTRB(24.h, 8.v, 311.h, 8.v), onTap: () {onTapClose(context);})); } 
/// Section Widget
Widget _buildFrame(BuildContext context) { return Container(padding: EdgeInsets.symmetric(horizontal: 45.h, vertical: 40.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgFrame), fit: BoxFit.cover)), child: Column(children: [SizedBox(height: 11.v), Container(height: 196.adaptSize, width: 196.adaptSize, padding: EdgeInsets.all(58.h), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder98), child: CustomImageView(imagePath: ImageConstant.imgEditColor, height: 80.adaptSize, width: 80.adaptSize, alignment: Alignment.center))])); } 
/// Section Widget
Widget _buildScanMyFace(BuildContext context) { return CustomElevatedButton(text: "lbl_scan_my_face".tr, margin: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 60.v)); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
