import 'bloc/create_authentication_fingerprint_bloc.dart';import 'models/create_authentication_fingerprint_model.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';class CreateAuthenticationFingerprintScreen extends StatelessWidget {const CreateAuthenticationFingerprintScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<CreateAuthenticationFingerprintBloc>(create: (context) => CreateAuthenticationFingerprintBloc(CreateAuthenticationFingerprintState(createAuthenticationFingerprintModelObj: CreateAuthenticationFingerprintModel()))..add(CreateAuthenticationFingerprintInitialEvent()), child: CreateAuthenticationFingerprintScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<CreateAuthenticationFingerprintBloc, CreateAuthenticationFingerprintState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(vertical: 36.v), child: Column(children: [Text("msg_setup_fingerprint".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 17.v), SizedBox(width: 249.h, child: Text("msg_you_can_use_fingerprint".tr, maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: theme.textTheme.bodyMedium!.copyWith(height: 1.71))), Spacer(flex: 37), CustomImageView(imagePath: ImageConstant.imgGroupPrimary196x196, height: 196.adaptSize, width: 196.adaptSize), SizedBox(height: 29.v), Text("msg_please_lift_and".tr, style: theme.textTheme.bodyMedium), Spacer(flex: 62)]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.fromLTRB(24.h, 8.v, 311.h, 8.v), onTap: () {onTapClose(context);})); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
