import 'bloc/faq_one_bloc.dart';import 'models/faq_one_model.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_subtitle.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_icon_button.dart';import 'package:hari_s_application3/widgets/custom_text_form_field.dart';class FaqOneScreen extends StatelessWidget {const FaqOneScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<FaqOneBloc>(create: (context) => FaqOneBloc(FaqOneState(faqOneModelObj: FaqOneModel()))..add(FaqOneInitialEvent()), child: FaqOneScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 32.v), child: Column(children: [_buildCs1(context), SizedBox(height: 39.v), _buildYou(context), SizedBox(height: 39.v), _buildCs2(context), SizedBox(height: 5.v)])), bottomNavigationBar: _buildReply(context))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapClose(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_support".tr)); } 
/// Section Widget
Widget _buildCs1(BuildContext context) { return Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(right: 23.h), child: Row(children: [Padding(padding: EdgeInsets.only(top: 56.v, bottom: 24.v), child: _buildAvatar(context)), Expanded(child: Padding(padding: EdgeInsets.only(left: 16.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 240.h, padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 7.v), Container(width: 190.h, margin: EdgeInsets.only(right: 17.h), child: Text("msg_hi_kitsbase_let".tr, maxLines: 3, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumOnPrimaryContainer_1.copyWith(height: 1.71)))])), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("lbl_08_20_am".tr, style: theme.textTheme.bodySmall))])))]))); } 
/// Section Widget
Widget _buildYou(BuildContext context) { return Column(children: [Align(alignment: Alignment.centerRight, child: Container(margin: EdgeInsets.only(left: 127.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.fillPink50.copyWith(borderRadius: BorderRadiusStyle.customBorderTL241), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 7.v), SizedBox(width: 163.h, child: Text("msg_how_to_create_a2".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumPink500_1.copyWith(height: 1.71)))]))), SizedBox(height: 8.v), Text("lbl_08_21_am".tr, style: theme.textTheme.bodySmall)]); } 
/// Section Widget
Widget _buildCs2(BuildContext context) { return Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(right: 23.h), child: Row(children: [Padding(padding: EdgeInsets.only(top: 56.v, bottom: 48.v), child: _buildAvatar(context)), Expanded(child: Container(margin: EdgeInsets.only(left: 16.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 12.v), decoration: AppDecoration.fillGray100.copyWith(borderRadius: BorderRadiusStyle.customBorderTL24), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 7.v), Container(width: 206.h, margin: EdgeInsets.only(right: 1.h), child: Text("msg_open_the_tradebase".tr, maxLines: 5, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumOnPrimaryContainer_1.copyWith(height: 1.71)))])))])), SizedBox(height: 8.v), Padding(padding: EdgeInsets.only(left: 80.h), child: Text("lbl_08_22_am".tr, style: theme.textTheme.bodySmall))]); } 
/// Section Widget
Widget _buildReply(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 24.h, right: 24.h, bottom: 60.v), child: BlocSelector<FaqOneBloc, FaqOneState, TextEditingController?>(selector: (state) => state.replyController, builder: (context, replyController) {return CustomTextFormField(controller: replyController, hintText: "msg_write_a_reply".tr, hintStyle: CustomTextStyles.bodyMediumGray600, textInputAction: TextInputAction.done, suffix: Container(margin: EdgeInsets.symmetric(horizontal: 30.h, vertical: 20.v), child: CustomImageView(imagePath: ImageConstant.imgUser2, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 64.v), contentPadding: EdgeInsets.only(left: 24.h, top: 23.v, bottom: 23.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL24);})); } 
/// Common widget
Widget _buildAvatar(BuildContext context) { return SizedBox(height: 48.adaptSize, width: 48.adaptSize, child: Stack(alignment: Alignment.bottomRight, children: [CustomImageView(imagePath: ImageConstant.imgImage, height: 48.adaptSize, width: 48.adaptSize, radius: BorderRadius.circular(24.h), alignment: Alignment.center), CustomIconButton(height: 20.adaptSize, width: 20.adaptSize, padding: EdgeInsets.all(2.h), decoration: IconButtonStyleHelper.outlineOnErrorContainerTL101, alignment: Alignment.bottomRight, child: CustomImageView(imagePath: ImageConstant.imgSettingsPink50020x20))])); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
