import 'bloc/verify_otp_bloc.dart';import 'models/verify_otp_model.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_elevated_button.dart';import 'package:hari_s_application3/widgets/custom_outlined_button.dart';import 'package:hari_s_application3/widgets/custom_pin_code_text_field.dart';class VerifyOtpScreen extends StatelessWidget {const VerifyOtpScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<VerifyOtpBloc>(create: (context) => VerifyOtpBloc(VerifyOtpState(verifyOtpModelObj: VerifyOtpModel()))..add(VerifyOtpInitialEvent()), child: VerifyOtpScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 34.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("lbl_verification".tr, style: theme.textTheme.headlineSmall)), SizedBox(height: 20.v), Align(alignment: Alignment.centerLeft, child: Container(width: 309.h, margin: EdgeInsets.only(right: 17.h), child: Text("msg_enter_4_digit_code".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: theme.textTheme.bodyMedium!.copyWith(height: 1.71)))), SizedBox(height: 36.v), BlocSelector<VerifyOtpBloc, VerifyOtpState, TextEditingController?>(selector: (state) => state.otpController, builder: (context, otpController) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});}), Spacer(), Opacity(opacity: 0.6, child: CustomElevatedButton(text: "lbl_continue".tr, buttonStyle: CustomButtonStyles.fillPrimaryTL24)), SizedBox(height: 16.v), CustomOutlinedButton(text: "lbl_resend_code".tr), SizedBox(height: 25.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.fromLTRB(24.h, 8.v, 311.h, 8.v), onTap: () {onTapClose(context);})); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
