import 'bloc/portfolio_stock_detail_v2_scroll_tab_container_bloc.dart';import 'models/portfolio_stock_detail_v2_scroll_tab_container_model.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/presentation/portfolio_stock_detail_v2_scroll_page/portfolio_stock_detail_v2_scroll_page.dart';import 'package:hari_s_application3/presentation/portfolio_stock_detail_vtwo_page/portfolio_stock_detail_vtwo_page.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_subtitle.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_elevated_button.dart';class PortfolioStockDetailV2ScrollTabContainerScreen extends StatefulWidget {const PortfolioStockDetailV2ScrollTabContainerScreen({Key? key}) : super(key: key);

@override PortfolioStockDetailV2ScrollTabContainerScreenState createState() =>  PortfolioStockDetailV2ScrollTabContainerScreenState();

static Widget builder(BuildContext context) { return BlocProvider<PortfolioStockDetailV2ScrollTabContainerBloc>(create: (context) => PortfolioStockDetailV2ScrollTabContainerBloc(PortfolioStockDetailV2ScrollTabContainerState(portfolioStockDetailV2ScrollTabContainerModelObj: PortfolioStockDetailV2ScrollTabContainerModel()))..add(PortfolioStockDetailV2ScrollTabContainerInitialEvent()), child: PortfolioStockDetailV2ScrollTabContainerScreen()); } 
 }

// ignore_for_file: must_be_immutable
class PortfolioStockDetailV2ScrollTabContainerScreenState extends State<PortfolioStockDetailV2ScrollTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 5, vsync: this); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return BlocBuilder<PortfolioStockDetailV2ScrollTabContainerBloc, PortfolioStockDetailV2ScrollTabContainerState>(builder: (context, state) {return SafeArea(child: Scaffold(appBar: _buildAppBar(context), body: SizedBox(width: double.maxFinite, child: Column(children: [SizedBox(height: 24.v), _buildNasdaq(context), SizedBox(height: 28.v), _buildTabview(context), SizedBox(height: 592.v, child: TabBarView(controller: tabviewController, children: [PortfolioStockDetailV2ScrollPage(), PortfolioStockDetailV2ScrollPage(), PortfolioStockDetailVtwoPage(), PortfolioStockDetailVtwoPage(), PortfolioStockDetailVtwoPage()]))]))));}); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapClose(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_stock_detail".tr)); } 
/// Section Widget
Widget _buildNasdaq(BuildContext context) { return Padding(padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [CustomImageView(imagePath: ImageConstant.imgSettingsGreenA70032x32, height: 32.adaptSize, width: 32.adaptSize), Padding(padding: EdgeInsets.only(left: 16.h, top: 7.v, bottom: 3.v), child: RichText(text: TextSpan(children: [TextSpan(text: "lbl_spot2".tr, style: CustomTextStyles.titleMedium16), TextSpan(text: "lbl_spotify2".tr, style: CustomTextStyles.labelLargeGray900_2)]), textAlign: TextAlign.left)), Spacer(), CustomElevatedButton(height: 20.v, width: 70.h, text: "lbl_0_903".tr, margin: EdgeInsets.symmetric(vertical: 6.v), buttonStyle: CustomButtonStyles.fillPink, buttonTextStyle: CustomTextStyles.labelLargeOnErrorContainer)])); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return Container(height: 27.v, width: 327.h, child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, labelColor: theme.colorScheme.onPrimaryContainer, labelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Eudoxus Sans', fontWeight: FontWeight.w700), unselectedLabelColor: appTheme.gray600, unselectedLabelStyle: TextStyle(fontSize: 12.fSize, fontFamily: 'Eudoxus Sans', fontWeight: FontWeight.w700), indicatorColor: appTheme.pink500, tabs: [Tab(child: Text("lbl_12h".tr)), Tab(child: Text("lbl_1d".tr)), Tab(child: Text("lbl_1w".tr)), Tab(child: Text("lbl_1m".tr)), Tab(child: Text("lbl_1y".tr))])); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
