import '../select_stocks_screen/widgets/stocklist_item_widget.dart';import 'bloc/select_stocks_bloc.dart';import 'models/select_stocks_model.dart';import 'models/stocklist_item_model.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_subtitle.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_search_view.dart';class SelectStocksScreen extends StatelessWidget {const SelectStocksScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<SelectStocksBloc>(create: (context) => SelectStocksBloc(SelectStocksState(selectStocksModelObj: SelectStocksModel()))..add(SelectStocksInitialEvent()), child: SelectStocksScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 6.v), child: Column(children: [SizedBox(height: 17.v), BlocSelector<SelectStocksBloc, SelectStocksState, TextEditingController?>(selector: (state) => state.searchController, builder: (context, searchController) {return CustomSearchView(controller: searchController, hintText: "msg_search_company".tr);}), SizedBox(height: 32.v), _buildStockList(context)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 64.h, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.only(left: 24.h, top: 8.v, bottom: 8.v), onTap: () {onTapClose(context);}), centerTitle: true, title: AppbarSubtitle(text: "lbl_select_stocks".tr)); } 
/// Section Widget
Widget _buildStockList(BuildContext context) { return BlocSelector<SelectStocksBloc, SelectStocksState, SelectStocksModel?>(selector: (state) => state.selectStocksModelObj, builder: (context, selectStocksModelObj) {return ListView.separated(physics: NeverScrollableScrollPhysics(), shrinkWrap: true, separatorBuilder: (context, index) {return SizedBox(height: 42.v);}, itemCount: selectStocksModelObj?.stocklistItemList.length ?? 0, itemBuilder: (context, index) {StocklistItemModel model = selectStocksModelObj?.stocklistItemList[index] ?? StocklistItemModel(); return StocklistItemWidget(model);});}); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
