import 'bloc/password_recovery_phone_number_bloc.dart';import 'models/password_recovery_phone_number_model.dart';import 'package:country_pickers/country.dart';import 'package:country_pickers/country_pickers.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_elevated_button.dart';import 'package:hari_s_application3/widgets/custom_phone_number.dart';class PasswordRecoveryPhoneNumberScreen extends StatelessWidget {const PasswordRecoveryPhoneNumberScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<PasswordRecoveryPhoneNumberBloc>(create: (context) => PasswordRecoveryPhoneNumberBloc(PasswordRecoveryPhoneNumberState(passwordRecoveryPhoneNumberModelObj: PasswordRecoveryPhoneNumberModel()))..add(PasswordRecoveryPhoneNumberInitialEvent()), child: PasswordRecoveryPhoneNumberScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 36.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text("msg_password_recovery".tr, style: theme.textTheme.headlineSmall), SizedBox(height: 17.v), Container(width: 268.h, margin: EdgeInsets.only(right: 58.h), child: Text("msg_enter_your_phone2".tr, maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyMediumGray600.copyWith(height: 1.71))), SizedBox(height: 36.v), BlocBuilder<PasswordRecoveryPhoneNumberBloc, PasswordRecoveryPhoneNumberState>(builder: (context, state) {
 return CustomPhoneNumber();}), SizedBox(height: 72.v), CustomElevatedButton(text: "lbl_send_otp_code".tr), SizedBox(height: 5.v)])))); }
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.fromLTRB(24.h, 8.v, 311.h, 8.v), onTap: () {onTapClose(context);})); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
