import 'bloc/otp_authentication_code_bloc.dart';import 'models/otp_authentication_code_model.dart';import 'package:flutter/material.dart';import 'package:hari_s_application3/core/app_export.dart';import 'package:hari_s_application3/widgets/app_bar/appbar_leading_iconbutton.dart';import 'package:hari_s_application3/widgets/app_bar/custom_app_bar.dart';import 'package:hari_s_application3/widgets/custom_elevated_button.dart';import 'package:hari_s_application3/widgets/custom_outlined_button.dart';import 'package:hari_s_application3/widgets/custom_pin_code_text_field.dart';class OtpAuthenticationCodeScreen extends StatelessWidget {const OtpAuthenticationCodeScreen({Key? key}) : super(key: key);

static Widget builder(BuildContext context) { return BlocProvider<OtpAuthenticationCodeBloc>(create: (context) => OtpAuthenticationCodeBloc(OtpAuthenticationCodeState(otpAuthenticationCodeModelObj: OtpAuthenticationCodeModel()))..add(OtpAuthenticationCodeInitialEvent()), child: OtpAuthenticationCodeScreen()); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h, vertical: 34.v), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Text("msg_enter_authentication".tr, style: theme.textTheme.headlineSmall)), SizedBox(height: 20.v), Align(alignment: Alignment.centerLeft, child: Container(width: 309.h, margin: EdgeInsets.only(right: 17.h), child: RichText(text: TextSpan(children: [TextSpan(text: "msg_enter_4_digit_code2".tr, style: theme.textTheme.bodyMedium), TextSpan(text: "lbl_84_999_999_999".tr, style: CustomTextStyles.bodyMediumPink500)]), textAlign: TextAlign.left))), SizedBox(height: 36.v), BlocSelector<OtpAuthenticationCodeBloc, OtpAuthenticationCodeState, TextEditingController?>(selector: (state) => state.otpController, builder: (context, otpController) {return CustomPinCodeTextField(context: context, controller: otpController, onChanged: (value) {otpController?.text = value;});}), SizedBox(height: 44.v), CustomElevatedButton(text: "lbl_continue".tr), SizedBox(height: 16.v), CustomOutlinedButton(text: "lbl_resend_code".tr), SizedBox(height: 5.v)])))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: double.maxFinite, leading: AppbarLeadingIconbutton(imagePath: ImageConstant.imgClose, margin: EdgeInsets.fromLTRB(24.h, 8.v, 311.h, 8.v), onTap: () {onTapClose(context);})); } 

/// Navigates to the previous screen.
onTapClose(BuildContext context) { NavigatorService.goBack(); } 
 }
